version: '3.4'

x-logging:
  &default-logging
  driver: journald

x-labels:
  &default-labels
  org.supernetworks.ci: ${CI:-false}
  org.supernetworks.version: ${RELEASE_VERSION:-latest}${RELEASE_CHANNEL:-}

services:
  spr-sample-plugin-minimal:
    container_name: spr-sample-plugin-minimal
    network_mode: ${NETWORK_MODE:-host}
    build:
      context: .
      labels: *default-labels
    logging: *default-logging
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - "${SUPERDIR}./state/plugins/spr_plugin_minimal:/state/plugins/spr_plugin_minimal"
      - "${SUPERDIR}./configs/plugins/spr_plugin_minimal/:/configs/plugins/spr_plugin_minimal"
#      - "${SUPERDIR}./state/api/:/state/api/:ro" #uncomment me for SPRBUS access
